import type { ModelProvider, ModelRequest } from "@eg/core";

type OllamaChatResponse = {
  message?: {
    content?: string;
    thinking?: string;
  };
};

export class OllamaProvider implements ModelProvider {
  readonly id: string;

  constructor(
    private readonly model = process.env.OLLAMA_DEFAULT_MODEL ?? "qwen3:8b",
    private readonly baseUrl = process.env.OLLAMA_BASE_URL ?? "http://127.0.0.1:11434"
  ) {
    this.id = `ollama:${this.model}`;
  }

  async complete(request: ModelRequest): Promise<string> {
    const response = await fetch(`${this.baseUrl}/api/chat`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: this.model,
        stream: false,
        think: false,
        format: request.responseFormat === "json" ? "json" : undefined,
        messages: [
          { role: "system", content: request.system },
          { role: "user", content: request.prompt }
        ],
        options: {
          temperature: request.temperature ?? 0.4,
          num_ctx: 8192
        }
      })
    });

    if (!response.ok) {
      const details = await response.text();
      throw new Error(
        `Ollama request failed (${response.status} ${response.statusText}): ${details}`
      );
    }

    const data = (await response.json()) as OllamaChatResponse;
    const content = data.message?.content?.trim();

    if (!content) {
      throw new Error(`Ollama model ${this.model} returned an empty response.`);
    }

    return content;
  }
}

export class MockProvider implements ModelProvider {
  readonly id = "mock";

  async complete(request: ModelRequest): Promise<string> {
    if (request.responseFormat === "json") {
      return JSON.stringify({
        generatedBy: this.id,
        objective: request.prompt,
        decisions: [
          "Preserve approved upstream decisions.",
          "Make assumptions explicit.",
          "Keep outputs production-oriented."
        ],
        risks: ["Mock output is not suitable for final production decisions."]
      }, null, 2);
    }

    return [
      "# Mock Artifact",
      "",
      request.prompt,
      "",
      "## Note",
      "This was generated by the fallback mock provider."
    ].join("\n");
  }
}

export async function checkOllama(
  baseUrl = process.env.OLLAMA_BASE_URL ?? "http://127.0.0.1:11434"
): Promise<{ ok: boolean; models: string[]; error?: string }> {
  try {
    const response = await fetch(`${baseUrl}/api/tags`);
    if (!response.ok) {
      return { ok: false, models: [], error: `${response.status} ${response.statusText}` };
    }
    const data = await response.json() as { models?: Array<{ name?: string }> };
    return {
      ok: true,
      models: (data.models ?? []).map(item => item.name ?? "").filter(Boolean)
    };
  } catch (error) {
    return {
      ok: false,
      models: [],
      error: error instanceof Error ? error.message : String(error)
    };
  }
}
