export const traderFrameCreativeSystem = {
  product: {
    name: "TraderFrame",
    category: "Private trading decision intelligence",
    definition:
      "A private platform that interprets market structure, events, sentiment, flows, technical evidence, and risk context to form an explainable directional thesis.",
    wedge:
      "TraderFrame turns fragmented market evidence into one explainable, risk-aware trading decision.",
    actions: ["act", "wait", "reduce", "reject"] as const
  },
  concept: {
    id: "conviction-atlas",
    publicName: "Conviction Atlas",
    workingName: "Decision Landscape",
    metaphor:
      "A living topographic field of possible market futures where intelligence flows carve the terrain, contradictions fracture routes, risk reshapes the field, and conviction emerges as the strongest current path.",
    stages: ["observe", "correlate", "form-thesis", "challenge", "conviction", "execute"] as const
  },
  visualOperatingSystem: {
    intelligence: {
      rule: "Represent meaning, not generic data.",
      primitive: "living-thread",
      behaviours: ["merge-on-agreement", "split-on-conflict", "fade-on-expiry", "intensify-with-importance"]
    },
    geometry: {
      rule: "Use contour fields generated by invisible forces.",
      primitives: ["topographic-contours", "vector-fields", "fluid-lines", "fracture-lines"]
    },
    materials: {
      rule: "Prefer optical and geological materials over mechanical chrome.",
      palette: ["smoked-glass", "obsidian", "polished-graphite", "optical-acrylic", "liquid-light"]
    },
    motion: {
      rule: "Every movement must explain a change in meaning.",
      sequence: ["accelerate", "branch", "collide", "slow", "stabilize", "resolve"]
    },
    landscape: {
      probability: "raises terrain and strengthens routes",
      risk: "creates valleys, instability, heat, or collapse",
      confidence: "increases elevation, clarity, and persistence",
      contradiction: "creates fractures and competing branches",
      liquidity: "creates flow and path continuity"
    },
    decision: {
      rule: "Conviction grows gradually from many possible paths.",
      behaviour: "weak paths recede while the strongest conditional route becomes legible"
    },
    interface: {
      rule: "The product interface must evolve from the landscape rather than overlay it.",
      transformation: ["contours-flatten", "surfaces-align", "panels-form", "cards-resolve", "workspace-emerges"]
    }
  },
  semantics: {
    verifiedEvidence: "cyan",
    selectedThesis: "violet",
    uncertainty: "amber",
    invalidation: "red",
    context: "neutral"
  },
  principles: [
    "Intelligence should flow, not float",
    "Probability should emerge, not appear",
    "Risk should reshape, not merely block",
    "Conviction should grow, not flash",
    "The interface should evolve, not overlay",
    "Motion must communicate reasoning",
    "Every visual must explain decision quality",
    "Probability, never certainty",
    "The user retains final control",
    "Private by design"
  ] as const,
  prohibitedClaims: [
    "guaranteed prediction",
    "certainty",
    "winning signal",
    "autonomous execution",
    "market-beating performance"
  ] as const,
  layers: {
    creativeThinking: [
      "product-strategy",
      "creative-direction",
      "information-architecture",
      "experience-narrative",
      "art-direction"
    ],
    production: [
      "concept-art",
      "storyboard-animatic",
      "design-system",
      "3d-assets",
      "motion-camera",
      "shader-vfx",
      "implementation",
      "qa-optimization",
      "deployment"
    ]
  }
} as const;

export type ConvictionAtlasStage =
  (typeof traderFrameCreativeSystem.concept.stages)[number];
