import type { PipelineDefinition, PipelineId } from "@eg/core";
export const pipelineOrder: PipelineId[] = ["strategy","concept-art","storyboard","design-system","modeling-3d","animation","shader-vfx","implementation","qa"];
export const pipelines: Record<PipelineId, PipelineDefinition> = {
"strategy": {
id: "strategy",
name: "Strategy Agent",
purpose: "Define product truth, audience, message hierarchy and narrative strategy.",
dependencies: [] as PipelineId[],
qualityThreshold: 8, maxAutomaticIterations: 2, humanApprovalRequired: true,
stages: [
{id:"product-intelligence",name:"Product Intelligence",objective:"Analyze product function, audience problem, business goal, differentiation and trust requirements.",outputName:"product-intelligence",outputKind:"json"},
{id:"audience-analysis",name:"Audience Analysis",objective:"Define audience needs, objections, knowledge level and decision criteria.",outputName:"audience-analysis",outputKind:"json"},
{id:"brand-extraction",name:"Brand Extraction",objective:"Translate product truth into brand principles and tone.",outputName:"brand-principles",outputKind:"json"},
{id:"message-hierarchy",name:"Message Hierarchy",objective:"Define primary message, proof points and CTA.",outputName:"message-hierarchy",outputKind:"json"},
{id:"narrative-strategy",name:"Narrative Strategy",objective:"Define the transformation from fragmented evidence to approved decision record.",outputName:"narrative-strategy",outputKind:"markdown"},
{id:"strategic-critique",name:"Strategic Critique",objective:"Critique clarity, differentiation, credibility and narrative potential.",outputName:"strategy-scorecard",outputKind:"scorecard"},
{id:"strategy-approval",name:"Strategy Approval Package",objective:"Assemble the strategy lock package.",outputName:"strategy-brief",outputKind:"markdown"},
]},
"concept-art": {
id: "concept-art",
name: "Concept Art Agent",
purpose: "Convert approved strategy into a distinctive and feasible visual concept.",
dependencies: ["strategy"] as PipelineId[],
qualityThreshold: 8, maxAutomaticIterations: 2, humanApprovalRequired: true,
stages: [
{id:"brand-analysis",name:"Visual Brand Analysis",objective:"Translate strategy into concrete visual principles.",outputName:"visual-principles",outputKind:"json"},
{id:"metaphor-generation",name:"Metaphor Generation",objective:"Generate a broad metaphor library.",outputName:"metaphor-library",outputKind:"json"},
{id:"metaphor-clustering",name:"Metaphor Clustering",objective:"Cluster metaphors and remove duplication.",outputName:"metaphor-clusters",outputKind:"json"},
{id:"direction-generation",name:"Direction Generation",objective:"Create three to five complete art directions.",outputName:"concept-directions",outputKind:"json"},
{id:"direction-critique",name:"Direction Critique",objective:"Score directions for originality, clarity, brand fit and feasibility.",outputName:"direction-scorecard",outputKind:"scorecard"},
{id:"direction-selection",name:"Direction Selection",objective:"Select a primary direction and fallback.",outputName:"selected-direction",outputKind:"markdown"},
{id:"art-direction",name:"Art Direction Specification",objective:"Define composition, camera, lighting, materials, color and atmosphere.",outputName:"art-direction",outputKind:"markdown"},
{id:"prompt-builder",name:"Prompt Builder",objective:"Create production-ready prompts for image generation.",outputName:"prompt-pack",outputKind:"prompt-pack"},
{id:"output-critique",name:"Output Critique",objective:"Define a critique and correction protocol.",outputName:"output-critique",outputKind:"scorecard"},
{id:"concept-approval",name:"Concept Approval Package",objective:"Assemble the concept lock.",outputName:"concept-lock",outputKind:"markdown"},
]},
"storyboard": {
id: "storyboard",
name: "Storyboard Agent",
purpose: "Convert the concept into a timed interactive cinematic experience.",
dependencies: ["concept-art"] as PipelineId[],
qualityThreshold: 8, maxAutomaticIterations: 2, humanApprovalRequired: true,
stages: [
{id:"narrative-decomposition",name:"Narrative Decomposition",objective:"Break the concept into narrative beats.",outputName:"narrative-beats",outputKind:"json"},
{id:"interaction-mapping",name:"Interaction Mapping",objective:"Map user interactions and state transitions.",outputName:"interaction-map",outputKind:"json"},
{id:"shot-generation",name:"Shot Generation",objective:"Generate candidate shots for each beat.",outputName:"shot-list",outputKind:"json"},
{id:"camera-language",name:"Camera Language",objective:"Define lens, movement, depth and transitions.",outputName:"camera-language",outputKind:"markdown"},
{id:"sequence-assembly",name:"Sequence Assembly",objective:"Assemble selected shots into sequence.",outputName:"sequence",outputKind:"json"},
{id:"timing-design",name:"Timing Design",objective:"Define timing for every scene.",outputName:"timing-sheet",outputKind:"json"},
{id:"continuity-critique",name:"Continuity Critique",objective:"Review spatial continuity and cognitive load.",outputName:"continuity-scorecard",outputKind:"scorecard"},
{id:"reduced-motion",name:"Reduced Motion Storyboard",objective:"Create reduced-motion alternatives.",outputName:"reduced-motion-storyboard",outputKind:"json"},
{id:"storyboard-approval",name:"Storyboard Approval Package",objective:"Assemble the experience lock.",outputName:"storyboard-lock",outputKind:"markdown"},
]},
"design-system": {
id: "design-system",
name: "Design System Agent",
purpose: "Create the shared interface, token and accessibility system.",
dependencies: ["storyboard"] as PipelineId[],
qualityThreshold: 8, maxAutomaticIterations: 2, humanApprovalRequired: true,
stages: [
{id:"interface-inventory",name:"Interface Inventory",objective:"Identify all UI components and information surfaces.",outputName:"interface-inventory",outputKind:"json"},
{id:"information-architecture",name:"Information Architecture",objective:"Rank information by hierarchy.",outputName:"information-architecture",outputKind:"json"},
{id:"token-generation",name:"Token Generation",objective:"Create visual and motion tokens.",outputName:"tokens",outputKind:"json"},
{id:"component-architecture",name:"Component Architecture",objective:"Define reusable component contracts.",outputName:"components",outputKind:"json"},
{id:"state-design",name:"State Design",objective:"Define component states.",outputName:"component-states",outputKind:"json"},
{id:"2d-3d-integration",name:"2D\u20133D Integration",objective:"Specify relationships between 3D objects and DOM UI.",outputName:"2d-3d-integration",outputKind:"markdown"},
{id:"accessibility-review",name:"Accessibility Review",objective:"Review keyboard, contrast, screen reader and reduced motion.",outputName:"accessibility-spec",outputKind:"markdown"},
{id:"design-approval",name:"Design System Approval",objective:"Assemble the design system lock.",outputName:"design-system-lock",outputKind:"markdown"},
]},
"modeling-3d": {
id: "modeling-3d",
name: "3D Modeling Agent",
purpose: "Specify production-ready 3D assets and environments.",
dependencies: ["design-system"] as PipelineId[],
qualityThreshold: 8, maxAutomaticIterations: 2, humanApprovalRequired: true,
stages: [
{id:"asset-breakdown",name:"Asset Breakdown",objective:"Create the full asset registry.",outputName:"asset-registry",outputKind:"json"},
{id:"asset-classification",name:"Asset Classification",objective:"Classify assets by role and complexity.",outputName:"asset-classification",outputKind:"json"},
{id:"technical-specification",name:"Technical Specification",objective:"Define scale, pivots, budgets, UVs, LODs and collision.",outputName:"asset-specifications",outputKind:"json"},
{id:"generation-plan",name:"Generation Plan",objective:"Assign procedural, manual or AI-assisted production methods.",outputName:"generation-plan",outputKind:"json"},
{id:"geometry-cleanup",name:"Geometry Cleanup Protocol",objective:"Define topology and export checks.",outputName:"geometry-cleanup",outputKind:"markdown"},
{id:"material-preparation",name:"Material Preparation",objective:"Define UV and material requirements.",outputName:"material-manifest",outputKind:"json"},
{id:"scene-assembly",name:"Scene Assembly",objective:"Define hierarchy, naming and origins.",outputName:"scene-assembly",outputKind:"json"},
{id:"optimization",name:"Optimization Plan",objective:"Define LOD, compression and mobile fallback.",outputName:"optimization-report",outputKind:"json"},
{id:"asset-approval",name:"3D Asset Approval Package",objective:"Assemble the 3D production lock.",outputName:"3d-assets-lock",outputKind:"markdown"},
]},
"animation": {
id: "animation",
name: "Animation Agent",
purpose: "Define meaningful motion and camera choreography.",
dependencies: ["modeling-3d"] as PipelineId[],
qualityThreshold: 8, maxAutomaticIterations: 2, humanApprovalRequired: true,
stages: [
{id:"motion-principles",name:"Motion Principle Extraction",objective:"Translate narrative into motion rules.",outputName:"motion-language",outputKind:"markdown"},
{id:"motion-vocabulary",name:"Motion Vocabulary",objective:"Define reusable motion behaviors.",outputName:"motion-vocabulary",outputKind:"json"},
{id:"timeline-planning",name:"Timeline Planning",objective:"Map animation events to storyboard timing.",outputName:"animation-registry",outputKind:"json"},
{id:"camera-choreography",name:"Camera Choreography",objective:"Create camera paths.",outputName:"camera-paths",outputKind:"json"},
{id:"object-animation",name:"Object Animation",objective:"Specify object animation clips.",outputName:"object-animation",outputKind:"json"},
{id:"interaction-animation",name:"Interaction Animation",objective:"Specify state-linked feedback.",outputName:"interaction-transitions",outputKind:"json"},
{id:"motion-critique",name:"Motion Critique",objective:"Review meaning, timing, accessibility and performance.",outputName:"motion-scorecard",outputKind:"scorecard"},
{id:"reduced-motion",name:"Reduced Motion Specification",objective:"Provide reduced-motion alternatives.",outputName:"reduced-motion-spec",outputKind:"json"},
{id:"animation-approval",name:"Animation Approval Package",objective:"Assemble the animation lock.",outputName:"animation-lock",outputKind:"markdown"},
]},
"shader-vfx": {
id: "shader-vfx",
name: "Shader & VFX Agent",
purpose: "Create narrative-driven shaders, particles and effects.",
dependencies: ["animation"] as PipelineId[],
qualityThreshold: 8, maxAutomaticIterations: 2, humanApprovalRequired: true,
stages: [
{id:"effect-inventory",name:"Effect Inventory",objective:"Define each effect and its narrative purpose.",outputName:"effect-inventory",outputKind:"json"},
{id:"shader-specification",name:"Shader Specification",objective:"Define uniforms, performance class and fallbacks.",outputName:"shader-registry",outputKind:"json"},
{id:"material-integration",name:"Material Integration",objective:"Map shaders to materials and states.",outputName:"materials",outputKind:"json"},
{id:"particle-systems",name:"Particle Systems",objective:"Define evidence, risk and approval particles.",outputName:"particle-systems",outputKind:"json"},
{id:"post-processing",name:"Post Processing",objective:"Define restrained post-processing.",outputName:"post-processing-config",outputKind:"json"},
{id:"performance-review",name:"Performance Review",objective:"Review shader and particle cost.",outputName:"shader-performance-report",outputKind:"scorecard"},
{id:"mobile-fallbacks",name:"Mobile Fallbacks",objective:"Define simplified mobile effects.",outputName:"mobile-fallbacks",outputKind:"json"},
{id:"vfx-approval",name:"Shader & VFX Approval",objective:"Assemble the VFX lock.",outputName:"vfx-lock",outputKind:"markdown"},
]},
"implementation": {
id: "implementation",
name: "Code Agent",
purpose: "Translate approved artifacts into technical implementation plans.",
dependencies: ["shader-vfx"] as PipelineId[],
qualityThreshold: 8, maxAutomaticIterations: 2, humanApprovalRequired: true,
stages: [
{id:"architecture",name:"Architecture Agent",objective:"Define application structure, state and loading.",outputName:"technical-architecture",outputKind:"markdown"},
{id:"scaffold",name:"Scaffold Agent",objective:"Define repository and module structure.",outputName:"repository-scaffold",outputKind:"json"},
{id:"scene-implementation",name:"Scene Implementation",objective:"Translate approved assets into scene modules.",outputName:"scene-plan",outputKind:"json"},
{id:"interaction",name:"Interaction Agent",objective:"Define input and interaction behavior.",outputName:"interaction-implementation",outputKind:"json"},
{id:"ui-integration",name:"UI Integration",objective:"Map the design system into responsive UI.",outputName:"ui-integration",outputKind:"json"},
{id:"asset-integration",name:"Asset Integration",objective:"Define loading, caching and error handling.",outputName:"asset-loading",outputKind:"json"},
{id:"performance",name:"Performance Agent",objective:"Define adaptive quality and LOD.",outputName:"performance-plan",outputKind:"json"},
{id:"accessibility",name:"Accessibility Agent",objective:"Define semantic DOM and fallback behavior.",outputName:"accessibility-implementation",outputKind:"markdown"},
{id:"code-review",name:"Code Review Agent",objective:"Review correctness and maintainability.",outputName:"code-review",outputKind:"scorecard"},
{id:"implementation-approval",name:"Implementation Approval",objective:"Assemble the implementation lock.",outputName:"implementation-lock",outputKind:"markdown"},
]},
"qa": {
id: "qa",
name: "QA & Optimization Agent",
purpose: "Verify functionality, accessibility, resilience and release readiness.",
dependencies: ["implementation"] as PipelineId[],
qualityThreshold: 8, maxAutomaticIterations: 2, humanApprovalRequired: true,
stages: [
{id:"acceptance-criteria",name:"Acceptance Criteria",objective:"Compile requirements from upstream artifacts.",outputName:"acceptance-tests",outputKind:"json"},
{id:"functional-testing",name:"Functional Testing",objective:"Define interaction and state test coverage.",outputName:"functional-test-plan",outputKind:"json"},
{id:"visual-regression",name:"Visual Regression",objective:"Define baseline and tolerance rules.",outputName:"visual-regression-report",outputKind:"report"},
{id:"cross-device",name:"Cross Device Testing",objective:"Define browser and device matrix.",outputName:"device-matrix",outputKind:"json"},
{id:"performance-testing",name:"Performance Testing",objective:"Define performance budgets.",outputName:"performance-report",outputKind:"report"},
{id:"accessibility-audit",name:"Accessibility Audit",objective:"Define accessibility verification.",outputName:"accessibility-report",outputKind:"report"},
{id:"failure-recovery",name:"Failure and Recovery",objective:"Test WebGL, asset and network failures.",outputName:"failure-recovery-plan",outputKind:"json"},
{id:"defect-prioritization",name:"Defect Prioritization",objective:"Define release severity levels.",outputName:"defect-policy",outputKind:"markdown"},
{id:"release-approval",name:"Release Approval",objective:"Assemble release checklist.",outputName:"release-checklist",outputKind:"markdown"},
]},
};
